

source 'https://github.com/ibroadlink/BLLibSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'


# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'supor' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!
    
    # Pods for LinWei
    
pod 'BLLet/BLLetCore', '~> 2.0'
pod 'BLLet/BLLetPlugins', '~> 2.0'
pod 'Masonry'
pod 'SVProgressHUD'
pod 'IQKeyboardManager'
pod 'MJExtension'
pod 'INTULocationManager'

pod 'Fabric'
pod 'Crashlytics'

end
